import duckdb
import os
import sys
import logging

log_file_path = "parts_gen.log"
created_tables = []

def setup_logging():
    """Configure logging for the script, logging to both console and a file."""
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    # Formatter for log messages
    formatter = logging.Formatter('%(asctime)s [%(levelname)s] %(message)s')

    # Console handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    # File handler
    file_handler = logging.FileHandler(log_file_path)
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

def check_or_create_table_dir(table: str, root: str) -> None:
    if not table in created_tables:
        os.makedirs(os.path.join(root, table), exist_ok=True)
        created_tables.append(table)



def get_existing_tables(conn):
    """
    Retrieve a list of existing tables in the DuckDB connection.

    Args:
        conn (duckdb.DuckDBPyConnection): Active DuckDB connection.

    Returns:
        set: A set of table names.
    """
    try:
        result = conn.execute("SHOW TABLES").fetchall()
        tables = {row[0] for row in result}
        return tables
    except Exception as e:
        logging.error(f"Error fetching tables: {e}")
        return set()

def export_tables_to_parquet(conn, tables, step, prefix):
    """
    Export specified tables to Parquet files.

    Args:
        conn (duckdb.DuckDBPyConnection): Active DuckDB connection.
        tables (list): List of table names to export.
        step (int): Current step number.
        output_dir (str): Directory to save Parquet files.
    """
    for table in tables:
        
        check_or_create_table_dir(table, prefix)
        parquet_file = os.path.join(prefix, table, f"{table}_{str(step).zfill(7)}.parquet")
        #parquet_file = f"s3://{bucket}/{prefix}/{table}/{table}_{str(step).zfill(7)}.parquet"
        try:
            logging.info(f"Exporting table '{table}' to '{parquet_file}'...")
            conn.execute(f"COPY {table} TO '{parquet_file}' (FORMAT 'parquet')")
            logging.info(f"Successfully exported '{table}' to '{parquet_file}'.")
        except Exception as e:
            logging.error(f"Failed to export table '{table}': {e}")

def main():
    # Initialize logging
    setup_logging()

    # Configuration Parameters
    DBGEN_STEPS = 10000          # Number of steps/chunks to generate
    SCALE_FACTOR = 3000        # Scale factor for dbgen
    CHILDREN = 3000             # Number of children per parent in dbgen
    STEP_START = 0            # Starting step number
    OUTPUT_DIR = "/data/output/gen/sf3000"  # Directory to save Parquet files
    OUTPUT_PREFIX = "gen/sf3000_s3"
    BUCKET = "output"
    DUCKDB_DATABASE = ":memory:"    # Use ':memory:' for in-memory DB or provide a file path

    # Create output directory if it doesn't exist
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    logging.info(f"Parquet files will be saved to '{OUTPUT_DIR}' (in table dir).")

    # Connect to DuckDB
    try:
        conn = duckdb.connect(database=DUCKDB_DATABASE)
        conn.execute('load tpch;')

        conn.execute("""
        CREATE SECRET secret1 (
            TYPE S3,
            KEY_ID 'localkey',
            SECRET 'localsecretkey',
            REGION 'eu-west-3',
            ENDPOINT '192.168.0.192:9000',
            URL_STYLE 'path',
            USE_SSL false
        );
        """
        )

       #  conn.execute("""
       #  CREATE SECRET secret1 (
       #      TYPE S3,
       #      KEY_ID 'AKIA2FAD7R26QK425N7V',
       #      SECRET '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',
       #      REGION 'eu-west-3',
       #      ENDPOINT 's3.eu-west-3.amazonaws.com'
       #  );
       #  """
       #  )

        logging.info(f"Connected to DuckDB database '{DUCKDB_DATABASE}'.")
    except Exception as e:
        logging.error(f"Failed to connect to DuckDB: {e}")
        sys.exit(1)

    # Get initial list of tables to identify new tables generated by dbgen
    initial_tables = get_existing_tables(conn)
    logging.info(f"Initial tables in the database: {initial_tables}")

    for step in range(STEP_START, CHILDREN ):
        logging.info(f"=== Step {step} ===")

        # Generate data using dbgen
        try:
            logging.info(f"Generating data with dbgen (sf={SCALE_FACTOR}, children={CHILDREN}, step={step})...")
            conn.execute(f"CALL dbgen(sf={SCALE_FACTOR}, children={CHILDREN}, step={step})")
            logging.info("Data generation completed.")
        except Exception as e:
            logging.error(f"dbgen failed at step {step}: {e}")
            continue  # Skip to the next step

        # Identify new tables generated by dbgen
        current_tables = get_existing_tables(conn)
        new_tables = current_tables - initial_tables
        if not new_tables:
            logging.warning(f"No new tables generated at step {step}.")
            continue
        logging.info(f"New tables generated at step {step}: {new_tables}")

        # Export new tables to Parquet
        export_tables_to_parquet(conn, new_tables, step, OUTPUT_DIR)

        # Optionally, drop the tables to free memory
        for table in new_tables:

            try:
                conn.execute(f"DROP TABLE IF EXISTS {table}")
                logging.info(f"Dropped table '{table}' after export.")
            except Exception as e:
                logging.error(f"Failed to drop table '{table}': {e}")

    # Close the DuckDB connection
    try:
        conn.close()
        logging.info("Closed DuckDB connection.")
    except Exception as e:
        logging.error(f"Error closing DuckDB connection: {e}")

    logging.info("Data generation and export process completed.")

if __name__ == "__main__":
    main()

