import asyncio
import duckdb
import os
import sys
import logging
import argparse
from concurrent.futures import ProcessPoolExecutor

log_file_path = "parts_gen.log"
created_tables = []


def setup_logging():
    """Configure logging for the script, logging to both console and a file."""
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    # Formatter for log messages
    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")

    # Console handler
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    # File handler
    file_handler = logging.FileHandler(log_file_path)
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)


def check_or_create_table_dir(table: str, root: str) -> None:
    if not table in created_tables:
        os.makedirs(os.path.join(root, table), exist_ok=True)
        created_tables.append(table)


def get_existing_tables(conn):
    """
    Retrieve a list of existing tables in the DuckDB connection.

    Args:
        conn (duckdb.DuckDBPyConnection): Active DuckDB connection.

    Returns:
        set: A set of table names.
    """
    try:
        result = conn.execute("SHOW TABLES").fetchall()
        tables = {row[0] for row in result}
        return tables
    except Exception as e:
        logging.error(f"Error fetching tables: {e}")
        return set()


def export_tables_to_parquet(conn, tables, step, prefix):
    """
    Export specified tables to Parquet files.

    Args:
        conn (duckdb.DuckDBPyConnection): Active DuckDB connection.
        tables (list): List of table names to export.
        step (int): Current step number.
        output_dir (str): Directory to save Parquet files.
    """
    for table in tables:
        check_or_create_table_dir(table, prefix)
        parquet_file = os.path.join(
            prefix, table, f"{table}_{str(step).zfill(7)}.parquet"
        )
        # parquet_file = f"s3://{bucket}/{prefix}/{table}/{table}_{str(step).zfill(7)}.parquet"
        try:
            logging.info(f"Exporting table '{table}' to '{parquet_file}'...")
            conn.execute(f"COPY {table} TO '{parquet_file}' (FORMAT 'parquet')")
            logging.info(f"Successfully exported '{table}' to '{parquet_file}'.")
        except Exception as e:
            logging.error(f"Failed to export table '{table}': {e}")


def process_part_test(part, chunks, sf, output_dir):
    logging.info(f"processing part {part} out of {chunks} and saving to {output_dir}")



async def run_blocking_process_part(step, chunks, sf, output_dir):
    try:
        result = await asyncio.to_thread(process_part, step, chunks, sf, output_dir)
        return result
    except asyncio.CancelledError:
        print(f"Task {step}: Was canceled.")
        raise  # Re-raise if you want the cancellation to propagate
    except Exception as e:
        print(f"Task {step}: Encountered an exception - {e}")
        return e  # Or handle accordingly



def process_part(step, chunks, sf, output_dir):
    #output_dir = f"{output_dir}_{str(step).zfill(5)}"

    DUCKDB_DATABASE = (
        ":memory:"  # Use ':memory:' for in-memory DB or provide a file path
    )

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    logging.info(f"Parquet files will be saved to '{output_dir}' (in table dir).")

    # Connect to DuckDB
    try:
        conn = duckdb.connect(database=DUCKDB_DATABASE)
        conn.execute("load tpch;")


        logging.info(f"Connected to DuckDB database '{DUCKDB_DATABASE}'.")
    except Exception as e:
        logging.error(f"Failed to connect to DuckDB: {e}")
        sys.exit(1)
    
    # Get initial list of tables to identify new tables generated by dbgen
    initial_tables = get_existing_tables(conn)
    logging.info(f"Initial tables in the database: {initial_tables}")

    logging.info(f"=== Step {step} ===")

    # Generate data using dbgen
    try:
        logging.info(
            f"STEP {step}: Generating data with dbgen (sf={sf}, children={chunks}, step={step})..."
        )
        conn.execute(
            f"CALL dbgen(sf={sf}, children={chunks}, step={step})"
        )
        logging.info(f"STEP {step}: Data generation completed.")
    except Exception as e:
        logging.error(f"dbgen failed at step {step}: {e}")
        return  # Skip to the next step

    # Identify new tables generated by dbgen
    current_tables = get_existing_tables(conn)
    new_tables = current_tables - initial_tables
    if not new_tables:
        logging.warning(f"STEP {step}:  No new tables generated at step {step}.")
        return
    logging.info(f"STEP {step}: New tables generated at step {step}: {new_tables}")

    # Export new tables to Parquet
    export_tables_to_parquet(conn, new_tables, step, output_dir)

    # Optionally, drop the tables to free memory
    for table in new_tables:
        try:
            conn.execute(f"DROP TABLE IF EXISTS {table}")
            logging.info(f"STEP {step}: Dropped table '{table}' after export.")
        except Exception as e:
            logging.error(f"STEP {step}: Failed to drop table '{table}': {e}")

    # Close the DuckDB connection
    try:
        conn.close()
        logging.info(f"STEP {step}: Closed DuckDB connection.")
    except Exception as e:
        logging.error(f"STEP {step}: Error closing DuckDB connection: {e}")


async def main():
    # Initialize logging
    setup_logging()

    parser = argparse.ArgumentParser(
        description="Generate TPC-H Benchmark parquet data using duckdb."
    )
    # Add arguments
    parser.add_argument(
        "--sf",
        type=int,
        default=1,
        help="Scale Factor (default is 1, range: 1, 3, 10, 30, 100, 300, 1000, 3000).",
    )
    parser.add_argument(
        "--parts",
        type=int,
        default=10,
        help="Number of parquet files (default is 10). 0 for no partitioning.",
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        default=None,
        help="Output location on disk.",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        required=False,
        default=2,
        help="Number of concurrent processes",
    )
    # Parse the arguments from the command line
    args = parser.parse_args()

    # Configuration Parameters
    # DBGEN_STEPS = 10000          # Number of steps/chunks to generate
    SCALE_FACTOR = args.sf  # Scale factor for dbgen
    CHILDREN = args.parts  # Number of children per parent in dbgen
    STEP_START = 0  # Starting step number
    CONCURRENCY = args.concurrency
    OUTPUT_DIR = (
        args.output
    )  # "/home/jeroen/data/gen/sf3001"  # Directory to save Parquet files


    # for step in range(STEP_START, CHILDREN):
    max_workers = CONCURRENCY  
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        loop = asyncio.get_running_loop()
        tasks = [
            loop.run_in_executor(executor, process_part, step, CHILDREN, SCALE_FACTOR, OUTPUT_DIR)
            for step in range(STEP_START, CHILDREN)
        ]


        results = await asyncio.gather(*tasks, return_exceptions=True)


        # results = await asyncio.gather(
        #     *[run_blocking_process_part(step, CHILDREN, SCALE_FACTOR, OUTPUT_DIR) 
        #     for step in range(STEP_START, CHILDREN)], return_exceptions=True
        # )

    print(f"{results=}")

    # BUCKET = "output"
    # DUCKDB_DATABASE = (
    #     ":memory:"  # Use ':memory:' for in-memory DB or provide a file path
    # )

    # # Create output directory if it doesn't exist
    # os.makedirs(OUTPUT_DIR, exist_ok=True)
    # logging.info(f"Parquet files will be saved to '{OUTPUT_DIR}' (in table dir).")

    # # Connect to DuckDB
    # try:
    #     conn = duckdb.connect(database=DUCKDB_DATABASE)
    #     conn.execute("load tpch;")

    #     conn.execute("""
    #     CREATE SECRET secret1 (
    #         TYPE S3,
    #         KEY_ID 'localkey',
    #         SECRET 'localsecretkey',
    #         REGION 'eu-west-3',
    #         ENDPOINT '192.168.0.192:9000',
    #         URL_STYLE 'path',
    #         USE_SSL false
    #     );
    #     """)

    #     #  conn.execute("""
    #     #  CREATE SECRET secret1 (
    #     #      TYPE S3,
    #     #      KEY_ID 'AKIA2FAD7R26QK425N7V',
    #     #      SECRET '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',
    #     #      REGION 'eu-west-3',
    #     #      ENDPOINT 's3.eu-west-3.amazonaws.com'
    #     #  );
    #     #  """
    #     #  )

    #     logging.info(f"Connected to DuckDB database '{DUCKDB_DATABASE}'.")
    # except Exception as e:
    #     logging.error(f"Failed to connect to DuckDB: {e}")
    #     sys.exit(1)

    # # Get initial list of tables to identify new tables generated by dbgen
    # initial_tables = get_existing_tables(conn)
    # logging.info(f"Initial tables in the database: {initial_tables}")

    # for step in range(STEP_START, CHILDREN):
    #     logging.info(f"=== Step {step} ===")

    #     # Generate data using dbgen
    #     try:
    #         logging.info(
    #             f"Generating data with dbgen (sf={SCALE_FACTOR}, children={CHILDREN}, step={step})..."
    #         )
    #         conn.execute(
    #             f"CALL dbgen(sf={SCALE_FACTOR}, children={CHILDREN}, step={step})"
    #         )
    #         logging.info("Data generation completed.")
    #     except Exception as e:
    #         logging.error(f"dbgen failed at step {step}: {e}")
    #         continue  # Skip to the next step

    #     # Identify new tables generated by dbgen
    #     current_tables = get_existing_tables(conn)
    #     new_tables = current_tables - initial_tables
    #     if not new_tables:
    #         logging.warning(f"No new tables generated at step {step}.")
    #         continue
    #     logging.info(f"New tables generated at step {step}: {new_tables}")

    #     # Export new tables to Parquet
    #     export_tables_to_parquet(conn, new_tables, step, OUTPUT_DIR)

    #     # Optionally, drop the tables to free memory
    #     for table in new_tables:
    #         try:
    #             conn.execute(f"DROP TABLE IF EXISTS {table}")
    #             logging.info(f"Dropped table '{table}' after export.")
    #         except Exception as e:
    #             logging.error(f"Failed to drop table '{table}': {e}")

    # # Close the DuckDB connection
    # try:
    #     conn.close()
    #     logging.info("Closed DuckDB connection.")
    # except Exception as e:
    #     logging.error(f"Error closing DuckDB connection: {e}")

    logging.info("Data generation and export process completed.")


if __name__ == "__main__":
    asyncio.run(main())
