import asyncio
import duckdb
import os
import sys
import logging
import argparse
from concurrent.futures import ProcessPoolExecutor

log_file_path = "parts_gen.log"
created_tables = []


def setup_logging():

    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)

    file_handler = logging.FileHandler(log_file_path)
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)


def check_or_create_table_dir(table: str, root: str) -> None:
    if not table in created_tables:
        os.makedirs(os.path.join(root, table), exist_ok=True)
        created_tables.append(table)


def get_existing_tables(conn: duckdb.DuckDBPyConnection) -> set[duckdb.table]:
    """
    Retrieves the names of existing tables in the DuckDB database connection.

    Args:
        conn (duckdb.DuckDBPyConnection): The DuckDB database connection object.

    Returns:
        set[duckdb.table]: A set containing the names of the existing tables in the database.
                           If an error occurs, an empty set is returned.

    Raises:
        None: All exceptions are caught and logged.
    """

    try:
        result = conn.execute("SHOW TABLES").fetchall()
        tables = {row[0] for row in result}
        return tables
    except Exception as e:
        logging.error(f"Error fetching tables: {e}")
        return set()


def export_tables_to_parquet(conn: duckdb.DuckDBPyConnection,
            tables: set[duckdb.table],
            step: int,
            output_path: str):
    """
    Exports a set of DuckDB tables to Parquet files.

    Args:
        conn (duckdb.DuckDBPyConnection): The DuckDB connection object.
        tables (set[duckdb.table]): A set of DuckDB tables to be exported.
        step (int): The step number to be included in the Parquet file name.
        output_path (str): The directory path where the Parquet files will be saved.

    Raises:
        Exception: If exporting any table fails, an error message is logged.
    """
    
    for table in tables:
        check_or_create_table_dir(table, output_path)
        parquet_file = os.path.join(
            output_path, table, f"{table}_{str(step).zfill(7)}.parquet"
        )

        try:
            logging.info(f"Exporting table '{table}' to '{parquet_file}'...")
            conn.execute(f"COPY {table} TO '{parquet_file}' (FORMAT 'parquet')")
            logging.info(f"Successfully exported '{table}' to '{parquet_file}'.")
        except Exception as e:
            logging.error(f"Failed to export table '{table}': {e}")


def process_part_test(part: int, chunks: int, sf: int, output_dir: str) -> None:
    logging.info(f"processing part {part} out of {chunks} and saving to {output_dir}")



def process_part(step: int, chunks: int, sf: int, output_dir: str) -> None:
    """
    Processes a part of the data generation pipeline using DuckDB and dbgen.
    Args:
        step (int): The current step in the data generation process.
        chunks (int): The number of child processes to use for data generation.
        sf (int): The scale factor for data generation.
        output_dir (str): The directory where the generated Parquet files will be saved.
    Returns:
        None
    This function performs the following steps:
    1. Creates the output directory if it does not exist.
    2. Connects to an in-memory DuckDB database and loads the TPCH extension.
    3. Logs the initial tables in the database.
    4. Executes the dbgen function to generate data.
    5. Logs the new tables generated by dbgen.
    6. Exports the new tables to Parquet files in the specified output directory.
    7. Drops the new tables from the database.
    8. Closes the DuckDB connection.
    """

    DUCKDB_DATABASE = (
        ":memory:"
    )

    os.makedirs(output_dir, exist_ok=True)
    logging.info(f"Parquet files will be saved to '{output_dir}' (in table dir).")

    try:
        conn = duckdb.connect(database=DUCKDB_DATABASE)
        conn.execute("load tpch;")


        logging.info(f"Connected to DuckDB database '{DUCKDB_DATABASE}'.")
    except Exception as e:
        logging.error(f"Failed to connect to DuckDB: {e}")
        sys.exit(1)
    
    initial_tables = get_existing_tables(conn)
    logging.info(f"Initial tables in the database: {initial_tables}")

    logging.info(f"=== Step {step} ===")

    try:
        logging.info(
            f"STEP {step}: Generating data with dbgen (sf={sf}, children={chunks}, step={step})..."
        )
        conn.execute(
            f"CALL dbgen(sf={sf}, children={chunks}, step={step})"
        )
        logging.info(f"STEP {step}: Data generation completed.")
    except Exception as e:
        logging.error(f"dbgen failed at step {step}: {e}")
        return

    current_tables = get_existing_tables(conn)
    new_tables = current_tables - initial_tables
    
    if not new_tables:
        logging.warning(f"STEP {step}:  No new tables generated at step {step}.")
        return
    logging.info(f"STEP {step}: New tables generated at step {step}: {new_tables}")

    export_tables_to_parquet(conn, new_tables, step, output_dir)

    for table in new_tables:
        try:
            conn.execute(f"DROP TABLE IF EXISTS {table}")
            logging.info(f"STEP {step}: Dropped table '{table}' after export.")
        except Exception as e:
            logging.error(f"STEP {step}: Failed to drop table '{table}': {e}")

    try:
        conn.close()
        logging.info(f"STEP {step}: Closed DuckDB connection.")
    except Exception as e:
        logging.error(f"STEP {step}: Error closing DuckDB connection: {e}")


async def main():
    """
    Main function to generate TPC-H Benchmark parquet data using duckdb.

    This function sets up logging, parses command-line arguments, and uses a 
    ProcessPoolExecutor to run the data generation process concurrently.

    Command-line arguments:
        --sf (int): Scale Factor (default is 1, range: 1, 3, 10, 30, 100, 300, 1000, 3000).
        --parts (int): Number of parquet files (default is 10). 0 for no partitioning.
        --output (str): Output location on disk. This argument is required.
        --concurrency (int): Number of concurrent processes (default is 2).

    The function initializes the necessary parameters from the parsed arguments,
    sets up a process pool executor, and runs the data generation tasks concurrently.
    Any errors encountered during the execution are logged.

    Returns:
        None
    """
    setup_logging()

    parser = argparse.ArgumentParser(
        description="Generate TPC-H Benchmark parquet data using duckdb."
    )

    parser.add_argument(
        "--sf",
        type=int,
        default=1,
        help="Scale Factor (default is 1, range: 1, 3, 10, 30, 100, 300, 1000, 3000).",
    )

    parser.add_argument(
        "--parts",
        type=int,
        default=10,
        help="Number of parquet files (default is 10). 0 for no partitioning.",
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        default=None,
        help="Output location on disk.",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        required=False,
        default=2,
        help="Number of concurrent processes",
    )


    args = parser.parse_args()


    scale_factor = args.sf
    children = args.parts
    STEP_START = 0
    concurrency = args.concurrency
    output_dir = args.output


    max_workers = concurrency  
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        loop = asyncio.get_running_loop()
        tasks = [
            loop.run_in_executor(executor, process_part, step, children, scale_factor, output_dir)
            for step in range(STEP_START, children)
        ]


        errors = await asyncio.gather(*tasks, return_exceptions=True)

        for e in errors: 
            if e:
                logging.error(f"Errors happended:\n{errors=}")

    logging.info("Data generation and export process completed.")


if __name__ == "__main__":
    asyncio.run(main())
